Repository cse110-sp25-group6/cse110-sp25-group6, pull requests merged in 2025-05, with the labels that each got.

#19 Merging HTML + CSS Validator, added ADR
  .github/workflows/main.yml
  source/test/test-valid.css
  source/test/test-valid.html
  specs/adrs/05-11-25-html-css-validator.md
Labels: enhancement, Combination

#28 Finished phase1.md
  admin/cipipeline/phase1.md
Labels: documentation

#31 Added Jest ADR
  specs/adrs/05-11-25-unit-test.md
Labels: documentation

#49 Basic Collection
  .github/workflows/main.yml
  .vscode/settings.json
  source/card_data/common.json
  source/collection/cardComponent.css
  source/collection/cardComponent.js
  source/collection/collection.css
  source/collection/collection.html
  source/collection/collection.js
  source/collection/sortCards.test.js
  source/package-lock.json
  source/package.json
  source/util/utils.js
  specs/pitch.md
Labels: Collections team

#61 homepage
  homepage/index.html
  homepage/script.js
  homepage/style.css
  source/collection/collection.html
Labels: Priority: Medium, Card/homepage
